### ISSUE TITLE
Endereço duplicado

### ISSUE THREAD

**Issue by igorodrigues** [hibrido/mag-busca-cep#1]
Olá, estou com um problema na parte de checkout de uma loja que estou testando o módulo, tudo funciona beleza, porém em vez de inserir o bairro ele duplica o endereço, http://luamulher.com/, alguém pode me ajudar?

**Comment by missoxd** [comment]
Bom dia,

Então, esse módulo busca o input de rua por um data atributo (`[data-rua]`), e se não encontrar ele faz um fallback para os elementos contendo "[street][]" no atributo name (`[name*="[street][]"]`). Isso conforme o pedaço de código abaixo:

```
var $rua = $form.find('[data-rua]');
if ( ! $rua.length) {
    $rua = $form.find('[name*="[street][]"]');
    if ( ! $rua.length) {
        console.log('rua input not found');
        return;
    }
}
```

Como no checkout do Magento ele coloca dois campos de endereço com o mesmo nome para que no PHP seja retornado um array, o módulo acaba pegando os dois campos sem querer.

Está em nossa pauta para fazer o fallback pegar somente o primeiro elemento retornado, porem, no momento estamos sem tempo para fazer essa mudança, se você desejar pode fazer um pull request que estudamos e aceitamos o mesmo.

Para resolver isso rapidamente, se você tem acesso aos arquivos template do Magento, pode adicionar um data atributo ao primeiro campo de endereço (`[data-rua]`), que o módulo irá funcionar normalmente.

Abraços

**Comment by missoxd** [comment]
Referênciando o pull request #4
